=== FelixDobler/Backup/client/config-schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "logDir": {
            "description": "Root directory of all log files",
            "type": "string"
        },
        "email": {
            "description": "Email recipient for alerts",
            "type": "string"
        },
        "rsyncTargetHost": {
            "type": "string",
            "anyOf": [
                {"type": "string", "description": "Target Host as specified in ssh config", "pattern": "^[a-zA-Z0-9\\-_]+:"},
                {"const": "", "description": "Empty Target Host, indicating same host"}
            ]
        },
        "components": {
            "type": "object",
            "description": "Configuration of components to back up",
            "properties": {
                "os": {
                    "$ref": "#/definitions/osItemSchema"
                },
                "nextcloud": {
                    "$ref": "#/definitions/nextcloudItemSchema"
                }
            },
            "additionalProperties": {
                "$ref": "#/definitions/rsyncItemSchema"
            }
        }
    },
    "additionalProperties": false,
    "required": ["email", "rsyncTargetHost", "components"],
    "definitions": {
        "osItemSchema": {
            "type": "object",
            "additionalItems": false,
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "default": true
                },
                "script": {
                    "type": "string",
                    "const": "rsync_backup.sh"
                },
                "useDefaultFiles": {
                    "type": "boolean",
                    "default": true
                },
                "useDefaultExcludes": {
                    "type": "boolean",
                    "default": true
                },
                "additionalExcludes": {
                    "type": "array",
                    "default": [],
                    "items": {
                        "type": "string"
                    }
                },
                "additionalFiles": {
                    "type": "array",
                    "default": [],
                    "items": {
                        "type": "string"
                    }
                },
                "source": {
                    "type": "string",
                    "default": "/"
                },
                "dstRelativePath": {
                    "type": "string",
                    "default": ""
                }
            },
            "required": [
                "enabled"
            ]
        },
        "rsyncItemSchema": {
            "type": "object",
            "additionalItems": false,
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "source": {
                    "type": "string"
                },
                "dstRelativePath": {
                    "type": "string"
                },
                "script": {
                    "type": "string",
                    "oneOf": [
                        {"pattern": "^[a-zA-Z0-9\\-_\\.]+$", 
                        "description": "File path of the backup script relative to component folder"},
                        {"const": "", 
                        "descripton": "Empty file path, using default rsync_backup.sh script"}
                    ]
                }
            },
            "required": ["enabled", "source", "dstRelativePath"]
        },
        "nextcloudItemSchema": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "tmpBackupDir": {
                    "description": "Directory for temporary files created during the Nextcloud backup",
                    "type": "string"
                },
                "dockerMountDir": {
                    "description": "Directory where the Nextcloud data from the docker container is mounted to the host",
                    "type": "string"
                },
                "dstRelativePath": {
                    "type": "string",
                    "default": "nextcloud"
                },
                "script": {"const": "nextcloud_backup.sh"}
            },
            "required": [
                "tmpBackupDir",
                "dockerMountDir",
                "script",
                "dstRelativePath"
            ]
        }
    }
}

=== FelixDobler/Backup/client/config.json
{
    "logDir": "/root/backup_logs",
    "email": "felix.dobler.fd@gmail.com",
    "rsyncTargetHost": "backup:",
    "components": {
        "os": {
            "enabled": false,
            "script": "rsync_backup.sh",
            "source": "/",
            "useDefaultFiles": true,
            "useDefaultExcludes": true,
            "files": "files_linux",
            "excludeFile": "exclude",
            "dstRelativePath": "rootfs",
            "additionalFiles": ["/etc/hosts", "/etc/fstab"]
        },
        "nextcloud": {
            "enabled": true,
            "tmpBackupDir": "/backups/tmp/nextcloud",
            "dockerMountDir": "/nextcloud",
            "script": "nextcloud_backup.sh",
            "dstRelativePath": "nextcloud"
        },
        "abc": {
            "enabled": false,
            "source": "/doesntexist",
            "dstRelativePath": "abc",
            "script": ""
        }
    }
}
